output "resource_count" {
  description = "Number of resources created by the base module"
  value       = module.base.resource_count
}

output "random_ids" {
  description = "Random IDs generated by the base module"
  value       = module.base.random_ids
}
